# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo-z7-20:part0:1.0 [current_project]
set_property ip_output_repo c:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/CNT24.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/CNT24_ALARM.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/CNT60.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/CNT60_ALARM.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/DCOUNT24.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/DECODER.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/DE_SELECTER.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/param.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/LED_COLOR1.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/LED_COLOR2.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/LED_COLOR3.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/SEQUENCER.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/SEQ_ALARM_USE.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/SEQ_SELMODE.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/SEQ_SET_ALARM.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/SEQ_SET_TIME.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/SETUP_SW.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/secCOUNT.v
  C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/COUNT24_SEL.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/COUNT24_SEL.xdc
set_property used_in_implementation false [get_files C:/Local_Fuchu/Local_st202402/FPGA/COUNT24_SEL_4/COUNT24_SEL.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top COUNT24 -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef COUNT24.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file COUNT24_utilization_synth.rpt -pb COUNT24_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
